spring.application.name=split
spring.datasource.url=jdbc:mysql://localhost:3306/split
spring.datasource.username=root
spring.datasource.password=tushar@123
spring.jpa.hibernate.ddl-auto=update

#spring.security.users.name=tushar
#spring.security.users.password=1234
jwt.secret=q8L6zLr+TusharB4F2CNon9H9uXy1a3j8Yc6QyL1Jv0=

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sharmatushar2505@gmail.com
spring.mail.password=avmrgsuphugfdtnf

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

